name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  sqflite: ^2.3.0
  path: ^1.9.0
  uuid: ^4.5.1
  tflite_flutter: ^0.12.1
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fraud_model.tflite
    - assets/vocab.json
    - assets/jordan_bhai.svg